# Generated by Django 3.2.5 on 2021-07-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventtory',
            new_name='inventory',
        ),
    ]
