# Generated by Django 3.2.5 on 2021-07-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_inventtory_product_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membersship',
            new_name='membership',
        ),
    ]
