# Generated by Django 5.1.2 on 2024-10-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20241012_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitializationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_run', models.BooleanField(default=False)),
            ],
        ),
    ]
