# Generated by Django 5.1.2 on 2024-10-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_initializationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='initializationstatus',
            name='update_applied',
            field=models.BooleanField(default=False),
        ),
    ]
