# Generated by Django 5.1.2 on 2024-10-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_initializationstatus_update_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='initializationstatus',
            name='delete_applied',
            field=models.BooleanField(default=False),
        ),
    ]
